# Generated by Django 5.2.4 on 2025-08-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alter_documenttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(error_messages={'max_length': 'El nombre no debe superar los 255 caracteres.', 'unique': 'El tipo de documento ya está registrado.'}, max_length=255, unique=True),
        ),
    ]
