# Generated by Django 5.2.4 on 2025-08-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_documenttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, error_messages={'max_length': 'La descripción no debe superar los 1000 caracteres.'}, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True, error_messages={'max_length': 'La descripción no debe superar los 1000 caracteres.'}, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(error_messages={'max_length': 'El nombre no debe superar los 255 caracteres.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='diu_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'El tipo de DIU no debe superar los 255 caracteres.'}, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='document_number',
            field=models.CharField(blank=True, error_messages={'max_length': 'El número de documento no debe superar los 50 caracteres.'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(error_messages={'max_length': 'El nombre no debe superar los 255 caracteres.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='code',
            field=models.CharField(error_messages={'max_length': 'El código no debe superar los 50 caracteres.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(error_messages={'max_length': 'El nombre no debe superar los 255 caracteres.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='predeterminedprice',
            name='name',
            field=models.CharField(error_messages={'max_length': 'El nombre no debe superar los 255 caracteres.'}, max_length=255),
        ),
    ]
