# Generated by Django 5.2.4 on 2025-08-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_appointment_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('patient',), name='unique_active_history_per_patient'),
        ),
    ]
